import { LocalityInterface } from "../models/localities.model.js";

export const localitiesStore: LocalityInterface[] = [
  {
    name: "nigeria",
    zipCode: "",
    latitude: 9.082,
    longitude: 8.6753,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "lagos",
        zipCode: "",
        latitude: 6.5244,
        longitude: 3.3792,
        isCountry: false,
        isState: true,
        isCity: false,
        children: [
          {
            name: "ikeja",
            zipCode: "100001",
            latitude: 6.5958,
            longitude: 3.3469,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "surulere",
            zipCode: "101283",
            latitude: 6.4969,
            longitude: 3.3606,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "lekki",
            zipCode: "105102",
            latitude: 6.4474,
            longitude: 3.5528,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "victoria island",
            zipCode: "101241",
            latitude: 6.4281,
            longitude: 3.4219,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: ["vi"],
          },
          {
            name: "yaba",
            zipCode: "101245",
            latitude: 6.5147,
            longitude: 3.3724,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
        alias: [],
      },
      {
        name: "abuja",
        zipCode: "",
        latitude: 9.0579,
        longitude: 7.4951,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["fct", "federal capital territory"],
        children: [
          {
            name: "gwarinpa",
            zipCode: "900108",
            latitude: 9.1167,
            longitude: 7.4116,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "wuse",
            zipCode: "900288",
            latitude: 9.0576,
            longitude: 7.4895,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "asokoro",
            zipCode: "900231",
            latitude: 9.0331,
            longitude: 7.5243,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "karu",
            zipCode: "900101",
            latitude: 8.9928,
            longitude: 7.5725,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "nyanya",
            zipCode: "900103",
            latitude: 9.0561,
            longitude: 7.5789,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "katampe",
            zipCode: "900108",
            latitude: 9.0984,
            longitude: 7.4716,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "gwagwalada",
            zipCode: "901101",
            latitude: 8.9508,
            longitude: 7.0767,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "kano",
        zipCode: "",
        latitude: 12.0022,
        longitude: 8.592,
        isCountry: false,
        isState: true,
        isCity: false,
        children: [],
        alias: [],
      },
      {
        name: "anambra",
        zipCode: "",
        latitude: 6.2209,
        longitude: 6.937,
        isCountry: false,
        isState: true,
        isCity: false,
        children: [],
        alias: [],
      },
      {
        name: "benue",
        zipCode: "970001",
        latitude: 7.7312634,
        longitude: 8.538425,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "abia",
        zipCode: "440221",
        latitude: 5.1128008,
        longitude: 7.3651376,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "imo",
        zipCode: "460241",
        latitude: 5.489736,
        longitude: 7.0341973,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "rivers",
        zipCode: "500001",
        latitude: 4.7676576,
        longitude: 7.0188527,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "port harcourt",
            zipCode: "500001",
            latitude: 4.8156,
            longitude: 7.0498,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "obio-akpor",
            zipCode: "500102",
            latitude: 4.8947,
            longitude: 6.9722,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "enugu",
        zipCode: "400102",
        latitude: 6.4499833,
        longitude: 7.5000007,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "nsukka",
            zipCode: "410001",
            latitude: 6.8573,
            longitude: 7.3958,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "enugu north",
            zipCode: "400001",
            latitude: 6.4667,
            longitude: 7.5167,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "cross river",
        zipCode: "550101",
        latitude: 5.8671966,
        longitude: 8.5204774,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "akwa ibom",
        zipCode: "520101",
        latitude: 4.990237,
        longitude: 7.9974399,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "delta",
        zipCode: "320110",
        latitude: 5.5273061,
        longitude: 6.1784167,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "bayelsa",
        zipCode: "562101",
        latitude: 4.7629786,
        longitude: 6.028898,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "edo",
        zipCode: "310101",
        latitude: 6.6076575,
        longitude: 5.9722713,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "ekiti",
        zipCode: "360101",
        latitude: 7.736891,
        longitude: 5.2738326,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "taraba",
        zipCode: "672002",
        latitude: 8.0141334,
        longitude: 10.7376336,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "ogun",
        zipCode: "110001",
        latitude: 6.9788582,
        longitude: 3.4389293,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "abeokuta",
            zipCode: "110001",
            latitude: 7.1475,
            longitude: 3.3619,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "ijebu-ode",
            zipCode: "120001",
            latitude: 6.8167,
            longitude: 3.9167,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "osun",
        zipCode: "230232",
        latitude: 7.5484047,
        longitude: 4.4978307,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "oyo",
        zipCode: "211105",
        latitude: 8.2151249,
        longitude: 3.5642897,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "ibadan",
            zipCode: "200001",
            latitude: 7.3775,
            longitude: 3.947,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "ogbomosho",
            zipCode: "210001",
            latitude: 8.1335,
            longitude: 4.2404,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "kaduna",
        zipCode: "800001",
        latitude: 10.5105,
        longitude: 7.4165,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "zaria",
            zipCode: "810001",
            latitude: 11.0667,
            longitude: 7.7,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "kaduna north",
            zipCode: "800001",
            latitude: 10.5236,
            longitude: 7.439,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "katsina",
        zipCode: "820001",
        latitude: 12.9908,
        longitude: 7.6008,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "sokoto",
        zipCode: "840001",
        latitude: 13.0622,
        longitude: 5.2339,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "kebbi",
        zipCode: "860001",
        latitude: 12.4539,
        longitude: 4.1994,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "zamfara",
        zipCode: "880001",
        latitude: 12.1704,
        longitude: 6.2204,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "niger",
        zipCode: "920001",
        latitude: 9.9314,
        longitude: 5.5933,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "kwara",
        zipCode: "240001",
        latitude: 8.9669,
        longitude: 4.38,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "plateau",
        zipCode: "930001",
        latitude: 9.2182,
        longitude: 9.5179,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "nasarawa",
        zipCode: "950001",
        latitude: 8.5401,
        longitude: 8.3206,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "gwale",
            zipCode: "950001",
            latitude: 8.5167,
            longitude: 8.35,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "borno",
        zipCode: "600001",
        latitude: 11.8333,
        longitude: 13.15,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "yobe",
        zipCode: "620001",
        latitude: 12.2941,
        longitude: 11.9611,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "adamawa",
        zipCode: "640001",
        latitude: 9.3265,
        longitude: 12.3984,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "gombe",
        zipCode: "760001",
        latitude: 10.2897,
        longitude: 11.1674,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "bauchi",
        zipCode: "740001",
        latitude: 10.3158,
        longitude: 9.8442,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "jigawa",
        zipCode: "720001",
        latitude: 12.2276,
        longitude: 9.5616,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "kogi",
        zipCode: "260001",
        latitude: 7.7333,
        longitude: 6.7333,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "ondo",
        zipCode: "340001",
        latitude: 7.2571,
        longitude: 5.2058,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
      {
        name: "ebonyi",
        zipCode: "490001",
        latitude: 6.2649,
        longitude: 8.0137,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [],
      },
    ],
  },
  {
    name: "south africa",
    zipCode: "",
    latitude: -30.5595,
    longitude: 22.9375,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "gauteng",
        zipCode: "",
        latitude: -26.2708,
        longitude: 28.1123,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "johannesburg",
            zipCode: "2000",
            latitude: -26.2041,
            longitude: 28.0473,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "pretoria",
            zipCode: "0002",
            latitude: -25.7479,
            longitude: 28.2293,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "soweto",
            zipCode: "1818",
            latitude: -26.2681,
            longitude: 27.8586,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "western cape",
        zipCode: "",
        latitude: -33.2277,
        longitude: 21.8569,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "cape town",
            zipCode: "8001",
            latitude: -33.9249,
            longitude: 18.4241,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "kwazulu-natal",
        zipCode: "",
        latitude: -28.5305,
        longitude: 30.8958,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "durban",
            zipCode: "4001",
            latitude: -29.8587,
            longitude: 31.0218,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
    ],
  },
  {
    name: "kenya",
    zipCode: "",
    latitude: -0.0236,
    longitude: 37.9062,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "nairobi",
        zipCode: "",
        latitude: -1.2864,
        longitude: 36.8172,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["nairobi county"],
        children: [
          {
            name: "nairobi city",
            zipCode: "00100",
            latitude: -1.2921,
            longitude: 36.8219,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "mombasa",
        zipCode: "",
        latitude: -4.0435,
        longitude: 39.6682,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["mombasa county"],
        children: [
          {
            name: "mombasa city",
            zipCode: "80100",
            latitude: -4.0435,
            longitude: 39.6682,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "kisumu",
        zipCode: "",
        latitude: -0.0917,
        longitude: 34.7680,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["kisumu county"],
        children: [
          {
            name: "kisumu city",
            zipCode: "40100",
            latitude: -0.0917,
            longitude: 34.7680,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
    ],
  },
  {
    name: "ghana",
    zipCode: "",
    latitude: 7.9465,
    longitude: -1.0232,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "greater accra",
        zipCode: "",
        latitude: 5.6037,
        longitude: -0.1870,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "accra",
            zipCode: "GA-001",
            latitude: 5.6037,
            longitude: -0.1870,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
          {
            name: "tema",
            zipCode: "GA-234",
            latitude: 5.6698,
            longitude: 0.0167,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "ashanti",
        zipCode: "",
        latitude: 6.7467,
        longitude: -1.5246,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "kumasi",
            zipCode: "AK-039",
            latitude: 6.6885,
            longitude: -1.6244,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "western",
        zipCode: "",
        latitude: 5.1134,
        longitude: -2.1006,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "takoradi",
            zipCode: "WS-023",
            latitude: 4.8975,
            longitude: -1.7594,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
    ],
  },
  {
    name: "egypt",
    zipCode: "",
    latitude: 26.8206,
    longitude: 30.8025,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "cairo",
        zipCode: "",
        latitude: 30.0444,
        longitude: 31.2357,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["cairo governorate"],
        children: [
          {
            name: "cairo city",
            zipCode: "11511",
            latitude: 30.0444,
            longitude: 31.2357,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "alexandria",
        zipCode: "",
        latitude: 31.2001,
        longitude: 29.9187,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["alexandria governorate"],
        children: [
          {
            name: "alexandria city",
            zipCode: "21500",
            latitude: 31.2001,
            longitude: 29.9187,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "giza",
        zipCode: "",
        latitude: 30.0131,
        longitude: 31.2089,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["giza governorate"],
        children: [
          {
            name: "giza city",
            zipCode: "12111",
            latitude: 30.0131,
            longitude: 31.2089,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
    ],
  },
  {
    name: "ethiopia",
    zipCode: "",
    latitude: 9.1450,
    longitude: 40.4897,
    isCountry: true,
    isState: false,
    isCity: false,
    alias: [],
    children: [
      {
        name: "addis ababa",
        zipCode: "",
        latitude: 9.0320,
        longitude: 38.7469,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: ["addis ababa city administration"],
        children: [
          {
            name: "addis ababa city",
            zipCode: "1000",
            latitude: 9.0320,
            longitude: 38.7469,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
      {
        name: "oromia",
        zipCode: "",
        latitude: 8.5400,
        longitude: 39.2700,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "adama",
            zipCode: "1100",
            latitude: 8.5400,
            longitude: 39.2700,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: ["nazret"],
          },
        ],
      },
      {
        name: "amhara",
        zipCode: "",
        latitude: 11.5900,
        longitude: 37.3900,
        isCountry: false,
        isState: true,
        isCity: false,
        alias: [],
        children: [
          {
            name: "bahir dar",
            zipCode: "2000",
            latitude: 11.5900,
            longitude: 37.3900,
            isCountry: false,
            isState: false,
            isCity: true,
            children: [],
            alias: [],
          },
        ],
      },
    ],
  },
];
